server:
  port: 8083
  context-path: /
spring:
     thymeleaf:
        prefix: classpath:/templates/
        check-template-location: true
        suffix: .html
        encoding: UTF-8
        content-type: text/html
        mode: HTML5
        cache: false
     data:
        redis:
            repositories:
                enabled: false
